"""PlatformIO pre-build hook: regenerate include/build_info.h on every build.

Wire into platformio.ini with `extra_scripts = pre:tools/gen_build_info.py` once the
PlatformIO project exists. PlatformIO always builds before it uploads, so this runs on
every `pio run` and every `pio run -t upload` -- there is no manual version-bump step
and no way to flash a build without it embedding a fresh git hash and timestamp.
"""

import subprocess
from datetime import datetime, timezone

Import("env")  # noqa: F821 -- injected by PlatformIO at exec time

try:
    git_hash = subprocess.check_output(
        ["git", "rev-parse", "--short", "HEAD"], text=True
    ).strip()
    dirty = subprocess.call(["git", "diff", "--quiet"]) != 0
except (subprocess.CalledProcessError, FileNotFoundError):
    git_hash, dirty = "unknown", False

build_time = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

header = f"""// Auto-generated by tools/gen_build_info.py on every build.
// Do not edit by hand, do not commit, do not hand-bump a version number here.
#pragma once
#define FW_GIT_HASH "{git_hash}{"+dirty" if dirty else ""}"
#define FW_BUILD_TIME "{build_time}"
"""

with open("include/build_info.h", "w") as f:
    f.write(header)
