// LineaMini_C6 -- Phase 6: WiFi/OTA/MQTT/BLE scale/shot log.
//
// Boots the serial console, initializes the display + LVGL, touch, and the
// ported espresso UI, brings up WiFi (DHCP) + OTA + BLE scale + MQTT, then
// the GICAR machine-interface UART driver last (see the ordering note in
// setup()). Prints the build fingerprint as a repeating heartbeat.

#include <Arduino.h>
#include <WiFi.h>
#include <ArduinoOTA.h>
#include <lvgl.h>

// Auto-generated by tools/gen_build_info.py on every build. It does not exist
// until the first `pio run`; that is expected. Provides FW_GIT_HASH /
// FW_BUILD_TIME.
#include "build_info.h"

// Machine-interface layer: wraps gicar.cpp's raw protocol driver in the
// MachineState struct (connected/coffee_temp_c/brew_active/...) that ui.cpp
// actually reads.
#include "machine.h"

// Display + LVGL bring-up (ILI9488 panel via LovyanGFX, LVGL driver registration).
#include "display.h"

// Ported LVGL espresso UI (pure widget logic; reads machine/scale/settings state).
#include "ui.h"

// GT911 capacitive touch -> LVGL pointer indev (drives the UI's click callbacks).
#include "touch.h"

// NVS-persisted user settings (coffee temp, brew weight target, shot count, ...).
#include "settings.h"

// BLE coffee scale (Felicita Arc / Bookoo Themis) -- weight/flow for brew-by-weight.
#include "scale.h"

// Home Assistant MQTT discovery + state/command topics.
#include "mqtt.h"

// NVS-backed WiFi credential storage (falls back to secrets.h WIFI_SSID/PASSWORD).
#include "wifi_config.h"

// SoftAP + captive portal for first-time WiFi setup (no saved NVS credentials).
#include "wifi_ap.h"

// Compile-time WiFi/MQTT/OTA fallback credentials (gitignored; see secrets.h.example).
#include "secrets.h"

// Serial + TCP (port 4444) diagnostic log sink, used throughout gicar.cpp etc.
#include "wlog.h"

// LittleFS-backed shot history (start/end detection, temp/weight samples, JSON API).
#include "shot_log.h"

// ── WiFi + OTA ────────────────────────────────────────────────────────────────
//
// OTA runs in its own FreeRTOS task (this chip is single-core, so it still
// shares CPU time with loop() via the scheduler). Matches the reference
// bring-up's ota_task() exactly -- see the OTA-on-core-1/WiFiUDP note below.

// mDNS/OTA hostname. Per-env: the S3 env overrides via build_flags so both
// boards can be on the network at once during the port (same name = mDNS fight
// and OTA/wlog target the wrong board).
#ifndef DEVICE_HOSTNAME
#define DEVICE_HOSTNAME "linea-mini-c6"
#endif

static void ota_task(void*) {
    ArduinoOTA.setHostname(DEVICE_HOSTNAME);
    if (strlen(OTA_PASSWORD) > 0) ArduinoOTA.setPassword(OTA_PASSWORD);

    ArduinoOTA.onStart([]() {
        Serial.println("OTA start");
        ui_ota_start();
    });
    ArduinoOTA.onEnd([]()   { Serial.println("\nOTA done"); });
    ArduinoOTA.onError([](ota_error_t e) {
        Serial.printf("OTA error[%u]\n", e);
    });

    bool armed = false;
    for (;;) {
        if (WiFi.status() == WL_CONNECTED) {
            if (!armed) {
                ArduinoOTA.begin();
                armed = true;
                wlogf("[ota] ready\n");
            }
            ArduinoOTA.handle();
        } else {
            // WiFi dropped — disarm so we re-call begin() on next reconnect.
            // ArduinoOTA uses a UDP socket that must be re-bound after reconnect.
            if (armed) {
                ArduinoOTA.end();
                armed = false;
                wlogf("[ota] disarmed (WiFi down)\n");
            }
        }
        vTaskDelay(1);
    }
}

// Stored at init so wifi_tick() can retry without re-reading NVS every call.
static const char* s_wifi_ssid    = nullptr;
static const char* s_wifi_pass    = nullptr;
static uint32_t    s_wifi_retries = 0;   // number of explicit reconnect attempts

static void wifi_begin() {
    WiFi.disconnect(false);
    delay(100);
    WiFi.begin(s_wifi_ssid, s_wifi_pass);   // DHCP -- no static IP for this board
}

static void wifi_ota_init() {
    s_wifi_ssid = wifi_config_ssid();
    s_wifi_pass = wifi_config_pass();
    WiFi.mode(WIFI_STA);
    WiFi.setAutoReconnect(false);  // we drive retries manually via wifi_tick()
    wifi_begin();
    Serial.printf("Connecting to %s", s_wifi_ssid);

    uint32_t t = millis();
    while (WiFi.status() != WL_CONNECTED && millis() - t < 10000) {
        delay(250);
        Serial.print('.');
    }
    Serial.println();

    if (WiFi.status() == WL_CONNECTED) {
        Serial.printf("WiFi OK — IP: %s\n", WiFi.localIP().toString().c_str());
        // Local time = UTC + settings offset (settings-menu "Timezone" item).
        configTime(settings.tz_offset_min * 60L, 0, "pool.ntp.org", "time.nist.gov");
    } else {
        Serial.println("WiFi slow — retrying every 20s via wifi_tick()");
    }

    xTaskCreate(ota_task, "OTA", 8192, NULL, 2, NULL);
}

// Declared extern in ui.cpp (status line shows retry count while disconnected).
uint32_t wifi_retry_count() { return s_wifi_retries; }

// Called from loop() — retries WiFi every 20 s when not connected.
// setAutoReconnect is unreliable in practice; retries are driven manually here.
static void wifi_tick() {
    static uint32_t last_retry = 0;
    if (WiFi.status() == WL_CONNECTED) {
        last_retry = 0;  // reset so we retry quickly after any future disconnect
        return;
    }
    if (millis() - last_retry < 20000) return;
    last_retry = millis();
    s_wifi_retries++;
    wlogf("[wifi] not connected (status=%d) — retry #%lu\n", (int)WiFi.status(), s_wifi_retries);
    wifi_begin();
}

void setup() {
    Serial.begin(115200);
    // Never block on USB CDC writes: with no host draining the port, the
    // default tx timeout stalls loop() for seconds per burst of log prints,
    // freezing GICAR polling (shot timer jerky / brew stop missed). Drop
    // output instead — confirmed via HA history 2026-07-03: machine_online
    // flapped 4s-on/10s-off whenever no serial monitor was attached.
    Serial.setTxTimeoutMs(0);
    delay(100);

    // Panel init + lv_init() + LVGL display-driver registration. Must run before
    // ui_init(), which requires lv_disp_drv_register() to have completed.
    display_init();

    // Load NVS credentials/settings before WiFi/UI need them.
    wifi_config_init();
    settings_init();

    // Build the UI widget tree on the registered LVGL display.
    ui_init();
    lv_timer_handler();   // first render before WiFi blocks (~10s connect timeout)

    // Register the GT911 touch pointer indev. Must come after ui_init()/the
    // first lv_timer_handler() -- see the comment on touch_init() in touch.cpp.
    touch_init();

    // WiFi connects first -- BLE scanning starts only after WiFi is up, per the
    // reference bring-up's note about WiFi/BLE coexistence contention on this
    // chip's shared 2.4GHz radio (both stacks run concurrently once both are
    // live; watch for this during Phase 6 testing).
    wifi_ota_init();
    scale_init();
    mqtt_init();

    // Bring up the GICAR link via the machine layer (gicar_init() plus the
    // MachineState reset -- calling gicar_init() directly here would leave
    // `machine` never populated, since only machine_update() reads gicar's
    // parsed frames into it). Blocks ~3 s during the boot handshake / config
    // read before returning; its diagnostics route to Serial via the wlog shim.
    // Deliberately called LAST, after display/touch/UI/WiFi init: the
    // empirically-validated reference bring-up calls machine_init() dead last
    // in setup() too. ui.cpp already renders a sane placeholder ("--.-°C",
    // disconnected) before real data arrives, so this ordering costs nothing
    // functionally.
#ifdef GICAR_WIRE_TEST
    // Validate the new GICAR pin choice BEFORE any resoldering: blink both
    // pins in antiphase (3s hi / 3s lo, ~90s) so a DMM on the bare header pads
    // confirms which physical pin is which, independent of silk labels (see
    // the GICAR pin comment in platformio.ini for why this project no longer
    // trusts silk/wiki labels alone). Remove -DGICAR_WIRE_TEST once confirmed.
    Serial.printf("[gicar] WIRE TEST: blinking GPIO%d/GPIO%d for ~90s (antiphase, 3s)\n",
                  GICAR_RX_PIN, GICAR_TX_PIN);
    pinMode(GICAR_RX_PIN, OUTPUT);
    pinMode(GICAR_TX_PIN, OUTPUT);
    for (int i = 0; i < 30; i++) {
        digitalWrite(GICAR_RX_PIN, i & 1);
        digitalWrite(GICAR_TX_PIN, !(i & 1));
        delay(3000);
        lv_timer_handler();
    }
    gpio_reset_pin((gpio_num_t)GICAR_RX_PIN);
    gpio_reset_pin((gpio_num_t)GICAR_TX_PIN);
    Serial.println("[gicar] WIRE TEST done");
#endif

    machine_init();
    shot_log_init();
}

void loop() {
    // Heartbeat: printed on a ~2 s cadence (not one-shot) so a passive serial
    // monitor attach can always catch it. Driven off millis() rather than a
    // blocking delay so LVGL keeps rendering smoothly between prints.
    static uint32_t last_heartbeat_ms = 0;
    if (millis() - last_heartbeat_ms >= 2000) {
        last_heartbeat_ms = millis();
        Serial.printf("Firmware build: %s (%s)\n", FW_GIT_HASH, FW_BUILD_TIME);
    }

    // Drain Serial1, pump the GICAR poll/parse state machine, and update the
    // `machine` struct ui.cpp reads (connected/coffee_temp_c/brew_active/...).
    machine_update();
    shot_log_update();

    wifi_tick();
    mqtt_tick();
    wlog_tick();
    if (wifi_ap_active()) wifi_ap_handle();

    // Pump the UI (button events, screen transitions, label updates) and LVGL's
    // own timers/rendering. lv_timer_handler() must be called frequently for a
    // responsive display; LV_TICK_CUSTOM (lv_conf.h) sources time from millis().
    ui_tick();
    lv_timer_handler();

    delay(5);
}
