// LineaMini_C6 -- Phase 5 scaffold.
//
// Boots the serial console, initializes the display + LVGL, touch, and the
// ported espresso UI, then brings up the GICAR machine-interface UART driver
// on GPIO2 (TX) / GPIO3 (RX) last (see the ordering note in setup()). Prints
// the build fingerprint as a repeating heartbeat. WiFi/MQTT/BLE scale are
// stubbed at this phase (added in Phase 6).

#include <Arduino.h>
#include <lvgl.h>

// Auto-generated by tools/gen_build_info.py on every build. It does not exist
// until the first `pio run`; that is expected. Provides FW_GIT_HASH /
// FW_BUILD_TIME.
#include "build_info.h"

// Machine-interface layer: wraps gicar.cpp's raw protocol driver in the
// MachineState struct (connected/coffee_temp_c/brew_active/...) that ui.cpp
// actually reads.
#include "machine.h"

// Display + LVGL bring-up (ILI9488 panel via LovyanGFX, LVGL driver registration).
#include "display.h"

// Ported LVGL espresso UI (pure widget logic; reads machine/scale/settings state).
#include "ui.h"

// GT911 capacitive touch -> LVGL pointer indev (drives the UI's click callbacks).
#include "touch.h"

void setup() {
    Serial.begin(115200);
    delay(100);

    // Panel init + lv_init() + LVGL display-driver registration. Must run before
    // ui_init(), which requires lv_disp_drv_register() to have completed.
    display_init();

    // Register the GT911 touch pointer indev. LVGL indevs may register any time
    // before the first lv_timer_handler(), so doing it right after display_init()
    // (before the widget tree is built) is fine and keeps the ordering simple.
    touch_init();

    // Build the UI widget tree on the registered LVGL display.
    ui_init();

    // Bring up the GICAR link via the machine layer (gicar_init() plus the
    // MachineState reset -- calling gicar_init() directly here would leave
    // `machine` never populated, since only machine_update() reads gicar's
    // parsed frames into it). Blocks ~3 s during the boot handshake / config
    // read before returning; its diagnostics route to Serial via the wlog shim.
    // Deliberately called LAST, after display/touch/UI init: the empirically-
    // validated reference bring-up (Old Claude directories/esp32workbench/
    // firmware/lm_controller, iterated to v0.25 on this exact board/wiring)
    // calls machine_init() dead last in setup() too. ui.cpp already renders a
    // sane placeholder ("--.-°C", disconnected) before real data arrives, so
    // this ordering costs nothing functionally.
    machine_init();
}

void loop() {
    // Heartbeat: printed on a ~2 s cadence (not one-shot) so a passive serial
    // monitor attach can always catch it. Driven off millis() rather than a
    // blocking delay so LVGL keeps rendering smoothly between prints.
    static uint32_t last_heartbeat_ms = 0;
    if (millis() - last_heartbeat_ms >= 2000) {
        last_heartbeat_ms = millis();
        Serial.printf("Firmware build: %s (%s)\n", FW_GIT_HASH, FW_BUILD_TIME);
    }

    // Drain Serial1, pump the GICAR poll/parse state machine, and update the
    // `machine` struct ui.cpp reads (connected/coffee_temp_c/brew_active/...).
    machine_update();

    // Pump the UI (button events, screen transitions, label updates) and LVGL's
    // own timers/rendering. lv_timer_handler() must be called frequently for a
    // responsive display; LV_TICK_CUSTOM (lv_conf.h) sources time from millis().
    ui_tick();
    lv_timer_handler();

    delay(5);
}
