// LineaMini_C6 -- Phase 1 scaffold.
//
// Boots the serial console, prints the build fingerprint as a repeating
// heartbeat, and brings up the GICAR machine-interface UART driver on
// GPIO16 (TX) / GPIO17 (RX). Display, LVGL, touch, WiFi/MQTT/BLE are added in
// later phases.

#include <Arduino.h>

// Auto-generated by tools/gen_build_info.py on every build. It does not exist
// until the first `pio run`; that is expected. Provides FW_GIT_HASH /
// FW_BUILD_TIME.
#include "build_info.h"

// GICAR machine-interface UART driver (Serial1 on GPIO16/17, 9600 8N1, invert).
#include "gicar.h"

// Phase 2 display bring-up (raw ST7365P panel test pattern, no LVGL yet).
#include "display.h"

void setup() {
    Serial.begin(115200);
    delay(100);

    // Bring up the GICAR link. Blocks ~3 s during the boot handshake / config
    // read before returning; its diagnostics route to Serial via the wlog shim.
    gicar_init();

    // Light up the GDI panel and paint the bring-up test pattern. Phase 2 is a
    // one-shot visual smoke test -- nothing in loop() touches the display yet.
    display_init_and_test_pattern();
}

void loop() {
    // Printed repeatedly, not just once at boot: a passive serial monitor
    // attach (no reset signal sent) can always catch this within one
    // heartbeat period, rather than racing a one-shot boot-time print.
    Serial.printf("Firmware build: %s (%s)\n", FW_GIT_HASH, FW_BUILD_TIME);

    // Drain Serial1 and pump the GICAR poll/parse state machine each iteration.
    gicar_process();

    delay(2000);
}
